version: '3'
services: 
    api: 
        build: 
            context: ./api
        ports: 
            - '8081:8080'
            - '9229:9229'
        environment: 
            - PGDATABASE=postgres
            - PGHOST=db
            - PGUSER=postgres
            - PGPASSWORD=password
            - PGPORT=5432
        depends_on: 
            - db
        volumes: 
            - ./api:/app
            - /app/node_modules
    db: 
        build: 
            context: ./db
        volumes: 
            - db-volume:/var/lib/postgresql/data
        ports:
            - '5455:5432'
volumes: 
    db-volume: